### ISSUE TITLE
When SOAP namespace is default

### ISSUE THREAD

**Issue by zdeneksejcek** [potok-digital/soap#47]
Hi,

thanks for SOAP library for Elixir. I just tried to init WSDL and I discovered that all xpaths like:

**//#{protocol_ns}:types/xsd:schema/xsd:complexType**

expect protocol_ns to have a value. When SOAP is a default namespace, then protocol_ns == [] and all xpaths fail.

I can help with this one if you like.

**Comment by zdeneksejcek** [comment]
Ok ok, someone already fixed couple of problems in master, but it seems like there is more to fix.

**Comment by Nitrino** [comment]
Hi @zdeneksejcek. What problems still remain?
We will try to help or we will be glad to make any contribution.

**Comment by zdeneksejcek** [comment]
E.g. I can see some hardcoded namespaces in xpaths like:
**soap_action: ~x"./soap:operation/@soapAction"s**

Then, I came across issue with emtpy soapAction:
**<soap:operation soapAction=""></soap:operation>**
What is wrong about empty actions? WSDLs I happen to integrate with sometimes have empty actions.

Thank you!

**Comment by zdeneksejcek** [comment]
To be more specific:

`  defp get_operations(wsdl, _soap_version, protocol_ns) do
    wsdl
    |> xpath(
      ~x"//#{ns("definitions", protocol_ns)}/#{ns("binding", protocol_ns)}/#{ns("operation", protocol_ns)}"l,
      name: ~x"./@name"s,
      soap_action: ~x"./soap:operation/@soapAction"s
    ) |> Enum.reject(fn x -> x[:soap_action] == "" end)
  end
`

**Comment by Nitrino** [comment]
Fixed in #60
