### ISSUE TITLE
Support for imported Schema

### ISSUE THREAD

**Issue by zdeneksejcek** [potok-digital/soap#48]
Hi,

do you plan to support imported schema?
Example:

`<types>
<xsd:schema>
<xsd:import namespace="http://domain.com/" schemaLocation="https://domain.com/services?xsd=1"/>
</xsd:schema>
</types>`

Thanks!

**Comment by Nitrino** [comment]
As far as I remember, and if I understand you correctly, this was done in #30 PR

**Comment by zdeneksejcek** [comment]
Yes, but it only works from local files. AFAIK it doesn't support urls.

**Comment by Nitrino** [comment]
Oh, of course, we should add get xsd schema file by URL.
We will add this functionality in the near future, or you can send a PR.

**Comment by sigmen** [comment]
Fixed in #57
